fivebarn/Controllers/MetricsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using fivebarn.Models;

namespace fivebarn.Controllers
{
    public class MetricsController : Controller
    {
        private ModelsContext db = new ModelsContext();

        //
        // GET: /Metrics/
            [StatsFilterAttribute]
        public ActionResult Index()
        {
            return View(db.Metrics.ToList());
        }

        //
        // GET: /Metrics/Details/5
            [StatsFilterAttribute]
        public ActionResult Details(int id = 0)
        {
            Metrics metrics = db.Metrics.Find(id);
            if (metrics == null)
            {
                return HttpNotFound();
            }
            return View(metrics);
        }

        //
        // GET: /Metrics/Create
            [StatsFilterAttribute]
        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Metrics/Create

        [HttpPost]
        [StatsFilterAttribute]
        public ActionResult Create(Metrics metrics)
        {
            if (ModelState.IsValid)
            {
                db.Metrics.Add(metrics);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(metrics);
        }

        //
        // GET: /Metrics/Edit/5
            [StatsFilterAttribute]
        public ActionResult Edit(int id = 0)
        {
            Metrics metrics = db.Metrics.Find(id);
            if (metrics == null)
            {
                return HttpNotFound();
            }
            return View(metrics);
        }

        //
        // POST: /Metrics/Edit/5

        [HttpPost]
        [StatsFilterAttribute]
        public ActionResult Edit(Metrics metrics)
        {
            if (ModelState.IsValid)
            {
                db.Entry(metrics).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(metrics);
        }

        //
        // GET: /Metrics/Delete/5
            [StatsFilterAttribute]
        public ActionResult Delete(int id = 0)
        {
            Metrics metrics = db.Metrics.Find(id);
            if (metrics == null)
            {
                return HttpNotFound();
            }
            return View(metrics);
        }

        //
        // POST: /Metrics/Delete/5

        [HttpPost, ActionName("Delete")]
        [StatsFilterAttribute]
        public ActionResult DeleteConfirmed(int id)
        {
            Metrics metrics = db.Metrics.Find(id);
            db.Metrics.Remove(metrics);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

fivebarn/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        @Scripts.Render("http://impactstory.org/static/js/total-impact-item.js") <!-- ImpactStory -->
        @Scripts.Render("https://d1bxh8uas1mnw7.cloudfront.net/assets/embed.js") <!-- AltMetrics -->
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("ALM", "Metrics", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>